{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <PyTest_CT_15.test_file_005.Test_Credence_005 object at 0x000001CAEABB6850>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file_005.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "dec85e16-e46d-47ea-8add-08f4f9f23658-attachment.txt", "type": "text/plain"}], "start": 1690980359622, "stop": 1690980359623, "uuid": "1eda22d2-01dc-4f0b-927a-3796be7bdb78", "historyId": "3373f973f87d181b033c1208fbde30ae", "testCaseId": "3373f973f87d181b033c1208fbde30ae", "fullName": "test_file_005.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file_005"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-NHCNSLF"}, {"name": "thread", "value": "3732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_005"}]}